### PR TITLE
Sahaja

### PR DESCRIPTION
**Pull request by sahajakatta**
Dear Sir / Madam,

Kindly verify my submissions completed and checked in during internship from 9th December 2021 till 27 February 2022.

Submission details:
1. Dec 20 10:42 car_model.blend
2. Dec 27 18:06 dolphin_model.blend
3. Jan  3 13:38 fire_hydrant_model.blend
4. Jan 10 05:33 Interior_prop_model.blend
5. Jan 17 11:49 Keyboard_model.blend
6. Jan 24 13:42 lamp_model.blend
7. Jan 31 11:47 Spaceship_model.blend
8. Feb  7 15:03 vintage_telephone_model.blend

Description: 3D models created using Blender

License: CC-BY-SA 4.0

Certification: I certify that these are my original work.

Request you to kindly accept the pull request and generate an experience certificate as applicable.

Regards,
Sahaja

### CODE REVIEW

**Comment by obonac** [comment]
Dear Sahaja,

Thank you for the dedicated effort towards the internship assignments. We hope you had a good learning experience.

Your experience certificate shall be generated  within two (2) working days, subject to content verification and operational checkpoints being successful.

We appreciate your contributions towards Project VIKRAM, as an AyeAI intern, and look forward to having you as an active advocate of technology for inclusive growth.

Regards
Abhishek Choudhary
Founder, AyeAI Consulting

**Comment by obonac** [comment]
Please update your portfolio site as per guidance provided at
https://github.com/sahajaportfolio/sahajaportfolio.github.io/pull/1

Please check and escrow the following link for correctness. The same shall be used to certify your experience letters.
https://ayeinterns.github.io/ayeinterns-winter2021/sahaja/3js/

**Comment by obonac** [comment]
Escrowed link for certification http://web.archive.org/web/20220329005720/https://github.com/ayeinterns/ayeinterns-winter2021/issues/3

**Comment by obonac** [comment]
Correction to original pull request message.

Date of completion as per our records is 22-Feb-2022. @sahajakatta please confirm.

**Comment by sahajakatta** [comment]
> Correction to original pull request message.
> 
> Date of completion as per our records is 22-Feb-2022. @sahajakatta please confirm.

Yes, I confirm that the relieving date was 22nd February 2022.

**Comment by obonac** [comment]
Update confirmation escrowed at http://web.archive.org/web/20220329074534/https://github.com/ayeinterns/ayeinterns-winter2021/pull/1

**Pull request merged**
